"""Add product rich text fields and ticket type

Revision ID: 771b9d69d705
Revises: 643a3cb8927a
Create Date: 2026-06-26 00:18:33.216712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771b9d69d705'
down_revision: Union[str, Sequence[str], None] = '643a3cb8927a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_types_id'), 'ticket_types', ['id'], unique=False)
    op.add_column('products', sa.Column('highlights', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('terms', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('cancellation_policy', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('usage_guide', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'usage_guide')
    op.drop_column('products', 'cancellation_policy')
    op.drop_column('products', 'terms')
    op.drop_column('products', 'highlights')
    op.drop_index(op.f('ix_ticket_types_id'), table_name='ticket_types')
    op.drop_table('ticket_types')
    # ### end Alembic commands ###
